package xmminer.xmclient;

import java.util.*;

public class XMMinerFrame_Res_Ko extends java.util.ListResourceBundle
{
  static final Object[][] contents = new String[][]{
	{ "File", "파일" },
	{ "New", "새 프로젝트" },
	{ "Open", "열기" },
	{ "Save", "저장" },
	{ "Save_as_", "새이름으로..." },
	{ "Print", "출력"},
	{ "Exit", "종료" },
	{ "Edit", "편집" },
	{ "Delete", "삭제" },
	{ "Select_all", "모두선택" },
	{ "Unselect", "선택해제" },
	{ "Draw", "그리기" },
	{ "Add", "추가" },
	{ "Extract_from_file", "파일추출" },
	{ "Extract_from_DB", "DB추출" },
	{ "Partitioning", "데이터 분할" },
	{ "Sampling", "데이터 추출" },
	{ "Column_Compute", "컬럼 생성" },
	{ "Column_Select", "컬럼 선택" },
	{ "Data_Query", "데이터 선택" },
	{ "Regression", "회귀분석" },
	{ "Correlation", "상관분석" },
	{ "Association_rule", "연관규칙" },
	{ "Sequence_rule", "순차패턴규칙" },
	{ "Episode_rule", "Episode규칙" },
	{ "C4_5", "C4.5" },
	{ "Neural_network", "인공신경망" },
	{ "Prediction", "예측모델" },
	{ "Data", "데이터" },
	{ "Connect", "연결" },
	{ "Properties", "설정" },
	{ "Select", "선택" },
	{ "Run_menu", "실행" },
	{ "Run", "전체실행" },
	{ "Rerun", "재실행" },
	{ "Run_to_here", "여기까지 실행" },
	{ "Run_alone", "단독 실행" },
	{ "Help", "도움말" },
	{ "About", "대하여..." },
	{ "Open_File", "프로젝트 파일을 엽니다" },
	{ "Save_File", "프로젝트 파일을 저장합니다" },
	{ "Connect_node", "노드를 연결합니다" },
	{ "Properties_node", "노드의 입력치를 설정합니다" },
	{ "Run_all", "전체 시나리오를 실행합니다" },
	{ "RunAlone", "선택된 노드를 단독실행합니다" },
	{ "Help_about", "XM-Tool/Miner에 대하여..." },
	{ "Extract_From_File", "파일로부터 자료추출" },
	{ "Extract_From_DB", "DB로부터 자료추출" },
	{ "Association_Rule", "연관규칙 발견" },
	{ "Sequence_Rule", "순차패턴규칙 발견" },
	{ "Episode_Rule", "Episode규칙 발견" },
	{ "C4_51", "의사결정트리 C4.5 구축" },
	{ "Neural_Network", "인공신경망 생성 및 학습" },
	{ "Select_a_menu", "메뉴를 선택하세요." },
	{ "Project_changed_Save", "프로젝트 파일이 수정되었습니다. 저장하시겠습니까 ?" },
	{ "Project_changed", "Project changed" },
	{ "XM_Error_can_t_open", "XM-Error: 프로젝트 파일을 열 수 없습니다 !" },
	{ "XM_Error_can_t_write", "XM-Error: 프로젝트 파일을 저장할 수 없습니다 !" },
	{ "Project_already", "프로젝트 파일이 존재합니다. 덮어쓰시겠습니까 ?" },
	{ "File_exist", "File exist" },
	{ "Project_name_must_be", "프로젝트가 먼저 정의되어야 합니다 !" },
	{ "Crtical_change_found", "앞노드에서 심각한 변화가 발견되었습니다 : " },
	{ "Running_error_at", "에러가 발생하였습니다! : " },
	{ "Can_t_create_the_edge", "연결할 수 없습니다 !" },
	{ "Destination_unknown", "연결될 노드를 알 수 없습니다 !" },
	{ "ChooserMsg", "파일 또는 프로젝트를 선택하세요: " },
	{ "ModelFile", "모델 파일" },
	{ "ScenarioFile", "시나리오 프로젝트" }};
  public Object[][] getContents()
  {
    return contents;
  }
}