package xmminer.xmclient;

import java.util.*;

public class XMMinerFrame_Res_En extends java.util.ListResourceBundle
{
  static final Object[][] contents = new String[][]{
	{ "File", "File" },
	{ "New", "New" },
	{ "Open", "Open" },
	{ "Save", "Save" },
	{ "Save_as_", "Save as..." },
	{ "Print", "Print"},
	{ "Exit", "Exit" },
	{ "Edit", "Edit" },
	{ "Delete", "Delete" },
	{ "Select_all", "Select all" },
	{ "Unselect", "Unselect" },
	{ "Draw", "Draw" },
	{ "Add", "Add" },
	{ "Extract_from_file", "Extract from file" },
	{ "Extract_from_DB", "Extract from DB" },
	{ "Partitioning", "Partitioning" },
	{ "Sampling", "Sampling" },
	{ "Column_Compute", "Column Compute" },
	{ "Column_Select", "Column Select" },
	{ "Data_Query", "Data Query" },
	{ "Regression", "Regression" },
	{ "Correlation", "Correlation" },
	{ "Association_rule", "Association rule" },
	{ "Sequence_rule", "Sequence rule" },
	{ "Episode_rule", "Episode rule" },
	{ "C4_5", "C4.5" },
	{ "Neural_network", "Neural network" },
	{ "Prediction", "Prediction" },
	{ "Data", "Data" },
	{ "Connect", "Connect" },
	{ "Properties", "Properties" },
	{ "Select", "Select" },
	{ "Run_menu", "Run" },
	{ "Run", "Run" },
	{ "Rerun", "Rerun" },
	{ "Run_to_here", "Run to here" },
	{ "Run_alone", "Run alone" },
	{ "Help", "Help" },
	{ "About", "About" },
	{ "Open_File", "Open File" },
	{ "Save_File", "Save File" },
	{ "Connect_node", "Connect node" },
	{ "Properties_node", "Properties setting" },
	{ "Run_all", "Run All" },
	{ "RunAlone", "Run Alone" },
	{ "Help_about", "About XM-Tool/Miner..." },
	{ "Extract_From_File", "Extract From File" },
	{ "Extract_From_DB", "Extract From DB" },
	{ "Association_Rule", "Association Rule" },
	{ "Sequence_Rule", "Sequence Rule" },
	{ "Episode_Rule", "Episode Rule" },
	{ "C4_51", "C 4.5" },
	{ "Neural_Network", "Neural Network" },
	{ "Select_a_menu", "Select a menu" },
	{ "Project_changed_Save", "Project changed. Save it ?" },
	{ "Project_changed", "Project changed" },
	{ "XM_Error_can_t_open", "XM-Error: can\'t open " },
	{ "XM_Error_can_t_write", "XM-Error: can\'t write to " },
	{ "Project_already", "Project already exists. Overwrite it ?" },
	{ "File_exist", "File exist" },
	{ "Project_name_must_be", "Project name must be determined first." },
	{ "Crtical_change_found", "Crtical change found at " },
	{ "Running_error_at", "Running error at " },
	{ "Can_t_create_the_edge", "Can\'t create the edge" },
	{ "Destination_unknown", "Destination unknown" },
	{ "ChooserMsg", "Please choose a file or project: " },
	{ "ModelFile", "Model File" },
	{ "ScenarioFile", "Scenario Project" }};
  public Object[][] getContents()
  {
    return contents;
  }
}